debug: true

server:
  port: 8099

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  mvc:
    servlet:
      load-on-startup: 1